// Context Auth
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const FAILED_REGISTRATION = 'FAILED_REGISTRATION';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const FAILED_AUTHENTICATED_USER = 'FAILED_AUTHENTICATED_USER';
export const LOGOUT = 'LOGOUT';

// Context Users
export const FAILED_GET_USERS = 'FAILED_GET_USERS';
export const SUCCESSFUL_GET_USERS = 'SUCCESSFUL_GET_USERS';

// Contex Products
export const FAILED_GET_PRODUCTS = 'FAILED_GET_PRODUCTS';
export const SUCCESSFUL_GET_PRODUCTS = 'SUCCESSFUL_GET_PRODUCTS';
export const SUCCESSFUL_UPLOAD_FILE = 'SUCCESSFUL_UPLOAD_FILE';

// Context Recipes

// Context Orders

// Todos los Context
export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAN_ALERTS = 'CLEAN_ALERTS';
