// Context Auth
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const SUCCESSFUL_FORGOT_PASSWORD = 'SUCCESSFUL_FORGOT_PASSWORD';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const FAILED_AUTHENTICATED_USER = 'FAILED_AUTHENTICATED_USER';
export const LOGOUT = 'LOGOUT';

// Context Users
export const FAILED_GET_USERS = 'FAILED_GET_USERS';
export const SUCCESSFUL_GET_USERS = 'SUCCESSFUL_GET_USERS';
export const SUCCESSFUL_EDIT_PROFILE = 'SUCCESSFUL_EDIT_PROFILE';

// Contex Products
export const FAILED_GET_PRODUCT = 'FAILED_GET_PRODUCT';
export const FAILED_GET_PRODUCTS = 'FAILED_GET_PRODUCTS';
export const SUCCESSFUL_GET_PRODUCTS = 'SUCCESSFUL_GET_PRODUCTS';
export const SUCCESSFUL_GET_PRODUCT = 'SUCCESSFUL_GET_PRODUCT';
export const SUCCESSFUL_UPLOAD_FILE = 'SUCCESSFUL_UPLOAD_FILE';
export const SUCCESSFUL_CREATE_PRODUCT = 'SUCCESSFUL_CREATE_PRODUCT';
export const SUCCESSFUL_EDIT_PRODUCT = 'SUCCESSFUL_EDIT_PRODUCT';
export const SUCCESSFUL_DELETE_PRODUCT = 'SUCCESSFUL_DELETE_PRODUCT';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCTC';

// Context Recipes
export const FAILED_GET_RECIPE = 'FAILED_GET_RECIPE';
export const FAILED_GET_RECIPES = 'FAILED_GET_RECIPES';
export const SUCCESSFUL_GET_RECIPES = 'SUCCESSFUL_GET_RECIPES';
export const SUCCESSFUL_GET_RECIPE = 'SUCCESSFUL_GET_RECIPE';
export const SUCCESSFUL_CREATE_RECIPE = 'SUCCESSFUL_CREATE_RECIPE';
export const SUCCESSFUL_EDIT_RECIPE = 'SUCCESSFUL_EDIT_RECIPE';
export const SUCCESSFUL_DELETE_RECIPE = 'SUCCESSFUL_DELETE_RECIPE';
export const SELECTED_RECIPE = 'SELECTED_RECIPE';

// Context Orders

// Todos los Context
export const SWITCH_LOADING = 'SWITCH_LOADING_LOGIN';

// export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
